import type {
  AdminOrderRowItem,
  AdminOrderStatus,
  GradingStatus,
  OrderSellerPersona,
} from "./types";

export const parseLocalDate = (s: string) =>
  new Date(s.replace(/\//g, "-")).getTime();

// Deterministic UUID-lookalike so the mock data is SSR-safe.
export const mockUuid = (seq: number) => {
  const suffix = String(seq).padStart(12, "0");
  return `00000000-0000-4000-8${suffix.slice(0, 3)}-${suffix.slice(3, 7)}-${suffix.slice(7, 19)}`;
};

// TODO: [Supabase Wiring] Replace with real Supabase query from orders table
// Target Table: orders, order_items, profiles, grading_jobs | View / RPC: list_admin_orders
export const MOCK_ADMIN_ORDERS: AdminOrderRowItem[] = [
  {
    id: "ORD-2026-000001",
    orderNumber: "ORD-2026-000001",
    createdAt: "2026/1/8 10:30",
    status: "pending",
    orderKind: "merchant",
    cardName: "リザードンex SAR",
    cardGrade: "PSA 10",
    itemPrice: 8500,
    appraisalFee: 150,
    totalPaid: 8650,
    buyerId: mockUuid(101),
    buyerName: "陳大文",
    sellerId: mockUuid(201),
    sellerName: "張國榮",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "pending_grading",
    inboundTrackingNo: null,
    outboundTrackingNo: null,
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000002",
    orderNumber: "ORD-2026-000002",
    createdAt: "2026/1/12 16:45",
    status: "pending",
    orderKind: "member",
    cardName: "ピカチュウ VMAX UR",
    cardGrade: "BGS 9.5",
    itemPrice: 1200,
    appraisalFee: 0,
    totalPaid: 1200,
    buyerId: mockUuid(102),
    buyerName: "李小龍",
    sellerId: mockUuid(202),
    sellerName: "王祖賢",
    sellerPersona: "member",
    useAuthentication: false,
    gradingStatus: "not_applicable",
    inboundTrackingNo: null,
    outboundTrackingNo: null,
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000003",
    orderNumber: "ORD-2026-000003",
    createdAt: "2026/1/20 09:15",
    status: "pending",
    orderKind: "merchant",
    cardName: "月亮伊布 SAR",
    cardGrade: "PSA 9",
    itemPrice: 4500,
    appraisalFee: 150,
    totalPaid: 4650,
    buyerId: mockUuid(103),
    buyerName: "劉德華",
    sellerId: mockUuid(203),
    sellerName: "梁朝偉",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "pending_grading",
    inboundTrackingNo: null,
    outboundTrackingNo: null,
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000004",
    orderNumber: "ORD-2026-000004",
    createdAt: "2026/2/3 11:20",
    status: "custody",
    orderKind: "member",
    cardName: "Mewtwo GX UR",
    cardGrade: "BGS 10",
    itemPrice: 18000,
    appraisalFee: 150,
    totalPaid: 18150,
    buyerId: mockUuid(104),
    buyerName: "郭富城",
    sellerId: mockUuid(204),
    sellerName: "鄭秀文",
    sellerPersona: "member",
    useAuthentication: true,
    gradingStatus: "pending_grading",
    inboundTrackingNo: "SF1000000001",
    outboundTrackingNo: null,
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000005",
    orderNumber: "ORD-2026-000005",
    createdAt: "2026/2/10 14:00",
    status: "custody",
    orderKind: "merchant",
    cardName: "沙奈朵 SAR",
    cardGrade: "PSA 10",
    itemPrice: 42000,
    appraisalFee: 150,
    totalPaid: 42150,
    buyerId: mockUuid(105),
    buyerName: "張學友",
    sellerId: mockUuid(205),
    sellerName: "周潤發",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "passed_authentic",
    inboundTrackingNo: "SF1000000002",
    outboundTrackingNo: null,
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000006",
    orderNumber: "ORD-2026-000006",
    createdAt: "2026/2/18 13:10",
    status: "custody",
    orderKind: "member",
    cardName: "烈空坐 V SAR",
    cardGrade: "Raw",
    itemPrice: 3200,
    appraisalFee: 150,
    totalPaid: 3350,
    buyerId: mockUuid(106),
    buyerName: "梅艷芳",
    sellerId: mockUuid(206),
    sellerName: "劉嘉玲",
    sellerPersona: "member",
    useAuthentication: true,
    gradingStatus: "failed_fake",
    inboundTrackingNo: "SF1000000003",
    outboundTrackingNo: null,
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000007",
    orderNumber: "ORD-2026-000007",
    createdAt: "2026/3/2 10:45",
    status: "grading",
    orderKind: "merchant",
    cardName: "超夢 SAR",
    cardGrade: "PSA 10",
    itemPrice: 76000,
    appraisalFee: 150,
    totalPaid: 76150,
    buyerId: mockUuid(107),
    buyerName: "成龍",
    sellerId: mockUuid(207),
    sellerName: "甄子丹",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "pending_grading",
    inboundTrackingNo: "SF1000000004",
    outboundTrackingNo: null,
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000008",
    orderNumber: "ORD-2026-000008",
    createdAt: "2026/3/8 17:30",
    status: "grading",
    orderKind: "member",
    cardName: "耿鬼 VMAX",
    cardGrade: "PSA 9",
    itemPrice: 9500,
    appraisalFee: 150,
    totalPaid: 9650,
    buyerId: mockUuid(108),
    buyerName: "周杰倫",
    sellerId: mockUuid(208),
    sellerName: "蔡依林",
    sellerPersona: "member",
    useAuthentication: true,
    gradingStatus: "pending_grading",
    inboundTrackingNo: "SF1000000005",
    outboundTrackingNo: null,
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000009",
    orderNumber: "ORD-2026-000009",
    createdAt: "2026/3/15 09:00",
    status: "grading",
    orderKind: "merchant",
    cardName: "噴火龍 SAR",
    cardGrade: "BGS 9.5",
    itemPrice: 128000,
    appraisalFee: 150,
    totalPaid: 128150,
    buyerId: mockUuid(109),
    buyerName: "謝霆鋒",
    sellerId: mockUuid(209),
    sellerName: "楊千嬅",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "passed_authentic",
    inboundTrackingNo: "SF1000000006",
    outboundTrackingNo: null,
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000010",
    orderNumber: "ORD-2026-000010",
    createdAt: "2026/3/22 15:20",
    status: "grading",
    orderKind: "member",
    cardName: "路卡利歐 SAR",
    cardGrade: "PSA 10",
    itemPrice: 5800,
    appraisalFee: 150,
    totalPaid: 5950,
    buyerId: mockUuid(110),
    buyerName: "林憶蓮",
    sellerId: mockUuid(210),
    sellerName: "黃家駒",
    sellerPersona: "member",
    useAuthentication: true,
    gradingStatus: "pending_grading",
    inboundTrackingNo: "SF1000000007",
    outboundTrackingNo: null,
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000011",
    orderNumber: "ORD-2026-000011",
    createdAt: "2026/4/5 11:00",
    status: "shipped",
    orderKind: "merchant",
    cardName: "皮卡丘 SAR",
    cardGrade: "BGS 10",
    itemPrice: 22000,
    appraisalFee: 150,
    totalPaid: 22150,
    buyerId: mockUuid(111),
    buyerName: "張柏芝",
    sellerId: mockUuid(211),
    sellerName: "古天樂",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "passed_authentic",
    inboundTrackingNo: "SF1000000008",
    outboundTrackingNo: "SF2000000001",
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000012",
    orderNumber: "ORD-2026-000012",
    createdAt: "2026/4/12 14:40",
    status: "shipped",
    orderKind: "member",
    cardName: "快龍 SAR",
    cardGrade: "PSA 10",
    itemPrice: 14500,
    appraisalFee: 150,
    totalPaid: 14650,
    buyerId: mockUuid(112),
    buyerName: "陳奕迅",
    sellerId: mockUuid(212),
    sellerName: "楊丞琳",
    sellerPersona: "member",
    useAuthentication: true,
    gradingStatus: "passed_authentic",
    inboundTrackingNo: "SF1000000009",
    outboundTrackingNo: "SF2000000002",
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000013",
    orderNumber: "ORD-2026-000013",
    createdAt: "2026/4/18 10:10",
    status: "shipped",
    orderKind: "merchant",
    cardName: "噴火龍 VSTAR",
    cardGrade: "Raw",
    itemPrice: 6800,
    appraisalFee: 150,
    totalPaid: 6950,
    buyerId: mockUuid(113),
    buyerName: "梁詠琪",
    sellerId: mockUuid(213),
    sellerName: "吳彦祖",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "failed_fake",
    inboundTrackingNo: "SF1000000010",
    outboundTrackingNo: "SF2000000003",
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000014",
    orderNumber: "ORD-2026-000014",
    createdAt: "2026/5/4 16:00",
    status: "completed",
    orderKind: "merchant",
    cardName: "甲賀忍蛙 GX",
    cardGrade: "PSA 10",
    itemPrice: 95000,
    appraisalFee: 150,
    totalPaid: 95150,
    buyerId: mockUuid(114),
    buyerName: "鄧紫棋",
    sellerId: mockUuid(214),
    sellerName: "謝賢",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "passed_authentic",
    inboundTrackingNo: "SF1000000011",
    outboundTrackingNo: "SF2000000004",
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: true,
  },
  {
    id: "ORD-2026-000015",
    orderNumber: "ORD-2026-000015",
    createdAt: "2026/5/10 12:30",
    status: "completed",
    orderKind: "member",
    cardName: "烈空坐 VMAX",
    cardGrade: "BGS 9.5",
    itemPrice: 32000,
    appraisalFee: 150,
    totalPaid: 32150,
    buyerId: mockUuid(115),
    buyerName: "容祖兒",
    sellerId: mockUuid(215),
    sellerName: "李克勤",
    sellerPersona: "member",
    useAuthentication: true,
    gradingStatus: "passed_authentic",
    inboundTrackingNo: "SF1000000012",
    outboundTrackingNo: "SF2000000005",
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: true,
  },
  {
    id: "ORD-2026-000016",
    orderNumber: "ORD-2026-000016",
    createdAt: "2026/5/18 09:45",
    status: "completed",
    orderKind: "member",
    cardName: "水箭龜 SAR",
    cardGrade: "PSA 9",
    itemPrice: 18500,
    appraisalFee: 150,
    totalPaid: 18650,
    buyerId: mockUuid(116),
    buyerName: "蔡卓妍",
    sellerId: mockUuid(216),
    sellerName: "鍾欣潼",
    sellerPersona: "member",
    useAuthentication: true,
    gradingStatus: "passed_authentic",
    inboundTrackingNo: "SF1000000013",
    outboundTrackingNo: "SF2000000006",
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: true,
  },
  {
    id: "ORD-2026-000017",
    orderNumber: "ORD-2026-000017",
    createdAt: "2026/5/25 14:15",
    status: "completed",
    orderKind: "merchant",
    cardName: "妙蛙花 SAR",
    cardGrade: "BGS 10",
    itemPrice: 65000,
    appraisalFee: 150,
    totalPaid: 65150,
    buyerId: mockUuid(117),
    buyerName: "王嘉爾",
    sellerId: mockUuid(217),
    sellerName: "林俊傑",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "passed_authentic",
    inboundTrackingNo: "SF1000000014",
    outboundTrackingNo: "SF2000000007",
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: true,
  },
  {
    id: "ORD-2026-000018",
    orderNumber: "ORD-2026-000018",
    createdAt: "2026/6/2 11:50",
    status: "completed",
    orderKind: "member",
    cardName: "夢幻 SAR",
    cardGrade: "Raw",
    itemPrice: 2500,
    appraisalFee: 0,
    totalPaid: 2500,
    buyerId: mockUuid(118),
    buyerName: "薛凱琪",
    sellerId: mockUuid(218),
    sellerName: "方大同",
    sellerPersona: "member",
    useAuthentication: false,
    gradingStatus: "not_applicable",
    inboundTrackingNo: "SF1000000015",
    outboundTrackingNo: "SF2000000008",
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000019",
    orderNumber: "ORD-2026-000019",
    createdAt: "2026/6/8 10:20",
    status: "completed",
    orderKind: "member",
    cardName: "呆呆獸 SAR",
    cardGrade: "PSA 9",
    itemPrice: 780,
    appraisalFee: 0,
    totalPaid: 780,
    buyerId: mockUuid(119),
    buyerName: "衛蘭",
    sellerId: mockUuid(219),
    sellerName: "側田",
    sellerPersona: "member",
    useAuthentication: false,
    gradingStatus: "not_applicable",
    inboundTrackingNo: "SF1000000016",
    outboundTrackingNo: "SF2000000009",
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000020",
    orderNumber: "ORD-2026-000020",
    createdAt: "2026/6/15 15:00",
    status: "completed",
    orderKind: "member",
    cardName: "傑尼龜 SAR",
    cardGrade: "BGS 9.5",
    itemPrice: 1500,
    appraisalFee: 0,
    totalPaid: 1500,
    buyerId: mockUuid(120),
    buyerName: "謝安琪",
    sellerId: mockUuid(220),
    sellerName: "張敬軒",
    sellerPersona: "member",
    useAuthentication: false,
    gradingStatus: "not_applicable",
    inboundTrackingNo: "SF1000000017",
    outboundTrackingNo: "SF2000000010",
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000021",
    orderNumber: "ORD-2026-000021",
    createdAt: "2026/6/22 13:30",
    status: "cancelled",
    orderKind: "member",
    cardName: "小火龍 SAR",
    cardGrade: "Raw",
    itemPrice: 2200,
    appraisalFee: 0,
    totalPaid: 2200,
    buyerId: mockUuid(121),
    buyerName: "黃子華",
    sellerId: mockUuid(221),
    sellerName: "佘詩曼",
    sellerPersona: "member",
    useAuthentication: false,
    gradingStatus: "not_applicable",
    inboundTrackingNo: null,
    outboundTrackingNo: null,
    payoutMethod: "fps_manual",
    buyerReceivedConfirmed: false,
  },
  {
    id: "ORD-2026-000022",
    orderNumber: "ORD-2026-000022",
    createdAt: "2026/7/1 10:00",
    status: "cancelled",
    orderKind: "merchant",
    cardName: "急凍鳥 SAR",
    cardGrade: "PSA 9",
    itemPrice: 5600,
    appraisalFee: 150,
    totalPaid: 5750,
    buyerId: mockUuid(122),
    buyerName: "吳鎮宇",
    sellerId: mockUuid(222),
    sellerName: "張曼玉",
    sellerPersona: "merchant",
    useAuthentication: true,
    gradingStatus: "failed_fake",
    inboundTrackingNo: null,
    outboundTrackingNo: null,
    payoutMethod: "stripe_connect",
    buyerReceivedConfirmed: false,
  },
];

export const ORDER_STATUS_LABELS: Record<AdminOrderStatus, string> = {
  pending: "待處理",
  custody: "倉庫託管",
  grading: "鑑定中",
  shipped: "運送中",
  completed: "已完成",
  cancelled: "已取消",
};

export const GRADING_STATUS_LABELS: Record<GradingStatus, string> = {
  pending_grading: "待鑑定",
  passed_authentic: "已鑑定-真品",
  failed_fake: "已鑑定-偽品",
  not_applicable: "不適用",
};

export const PERSONA_LABELS: Record<OrderSellerPersona, string> = {
  merchant: "認證商戶",
  member: "個人散戶",
};

export function getOrderById(id: string): AdminOrderRowItem | undefined {
  return MOCK_ADMIN_ORDERS.find((o) => o.id === id);
}
