// Centralized preset chatrooms / messages bank
// All timestamps are ISO 8601 strings to support the Temporal HUD engine
export const INITIAL_CHATS = [
  {
    id: "chatId-A-BUYER-MERCHANT",
    partnerId: "HKCV-8839-44A",
    partnerAvatarUrl: "/asset/default-avator.webp",
    partnerName: "渡邊道館",
    partnerTier: "專業認證商戶",
    lastMessage: "· 渡邊道館 已接受您的出價。",
    unreadCount: 0,
    timestamp: "2026-06-28T10:00:00.000Z",
    messages: [
      {
        id: "m1_a",
        sender: "me",
        text: "老闆，這張噴火龍品相如何？有邊角磨損嗎？",
        timestamp: "2026-06-28T09:45:00.000Z",
      },
      {
        id: "m2_a",
        sender: "them",
        text: "師兄放心，卡面完美，四角尖尖，可以隨時提報平台代管交易。",
        timestamp: "2026-06-28T09:48:00.000Z",
      },
      {
        id: "m3_a",
        sender: "me",
        text: "好，那我直接提報一個專屬議價，麻煩確認一下。",
        timestamp: "2026-06-28T09:50:00.000Z",
      },
      {
        id: "txn-A",
        sender: "me",
        text: "· 渡邊道館 已接受您的出價。",
        timestamp: "2026-06-28T10:00:00.000Z",
        type: "special_transaction",
        specialData: {
          cardName: "Charizard ex SAR (噴火龍)",
          cardId: "sv2a-182",
          offerPrice: 44800,
          buyerName: "認證用戶",
          buyerId: "USR-PRESET-ME-001",
          sellerId: "HKCV-8839-44A",
          sellerName: "渡邊道館",
          initialStatus: "accepted",
        },
      },
    ],
  },
  {
    id: "chatId-B-BUYER-USER",
    partnerId: "USR-PRESET-B-001",
    partnerAvatarUrl: "/asset/default-avator.webp",
    partnerName: "信和執雞大師",
    partnerTier: "認證用戶",
    lastMessage: "這張皮卡丘 AR 放很久了，最低就這個價啦，不能再便宜了。",
    unreadCount: 0,
    timestamp: "2026-06-28T11:00:00.000Z",
    messages: [
      {
        id: "m1_b",
        sender: "me",
        text: "你好，請問 Pikachu AR 還有嗎？",
        timestamp: "2026-06-28T10:30:00.000Z",
      },
      {
        id: "m2_b",
        sender: "them",
        text: "還在的，這張是信和現貨，四角尖。",
        timestamp: "2026-06-28T10:35:00.000Z",
      },
      {
        id: "m3_b",
        sender: "me",
        text: "可以用 HK$ 320 交割嗎？",
        timestamp: "2026-06-28T10:40:00.000Z",
      },
      {
        id: "m4_b",
        sender: "them",
        text: "這張皮卡丘 AR 放很久了，最低就這個價啦，不能再便宜了。",
        timestamp: "2026-06-28T10:45:00.000Z",
      },
      {
        id: "txn-B",
        sender: "me",
        text: "· 您向 信和執雞大師 提報了 HK$ 320 的預期出價。",
        timestamp: "2026-06-28T11:00:00.000Z",
        type: "special_transaction",
        specialData: {
          cardName: "Pikachu AR (皮卡丘)",
          cardId: "sv2a-215",
          offerPrice: 320,
          buyerName: "認證用戶",
          buyerId: "USR-PRESET-ME-001",
          sellerId: "USR-PRESET-B-001",
          sellerName: "信和執雞大師",
          initialStatus: "pending",
        },
      },
    ],
  },
  {
    id: "chatId-C-SELLER-USER",
    partnerId: "USR-PRESET-C-001",
    partnerAvatarUrl: "/asset/default-avator.webp",
    partnerName: "九龍灣卡王",
    partnerTier: "認證買家",
    lastMessage: "· 九龍灣卡王 向您提報了 HK$ 3,200 的預期出價。",
    unreadCount: 1,
    timestamp: "2026-06-28T12:00:00.000Z",
    messages: [
      {
        id: "m1_c",
        sender: "them",
        text: "師兄，看中你掛出的月亮伊布 ex SAR 了，可以便宜點嗎？",
        timestamp: "2026-06-28T11:45:00.000Z",
      },
      {
        id: "m2_c",
        sender: "me",
        text: "這張剛過 PSA 10，品相有保障，你可以提個合理議價。",
        timestamp: "2026-06-28T11:50:00.000Z",
      },
      {
        id: "txn-C",
        sender: "them",
        text: "· 九龍灣卡王 向您提報了 HK$ 3,200 的預期出價。",
        timestamp: "2026-06-28T12:00:00.000Z",
        type: "special_transaction",
        specialData: {
          cardName: "Umbreon ex SAR (月亮伊布)",
          cardId: "sv6a-109",
          offerPrice: 3200,
          buyerName: "九龍灣卡王",
          buyerId: "USR-PRESET-C-001",
          sellerId: "USR-PRESET-ME-001",
          sellerName: "我",
          initialStatus: "pending",
        },
      },
    ],
  },
  {
    id: "chatId-D-SPECULATOR",
    partnerId: "USR-PRESET-D-001",
    partnerAvatarUrl: "/asset/default-avator.webp",
    partnerName: "秋葉原海外直送店",
    partnerTier: "專業認證商戶",
    lastMessage: "日本直郵，大概 3-5 天到香港，含中介保險。",
    unreadCount: 0,
    timestamp: "2026-06-28T14:00:00.000Z",
    messages: [
      {
        id: "m1_d",
        sender: "them",
        text: "您好，日本秋葉原直送全新未拆盒卡牌，含中介鑑定保險。",
        timestamp: "2026-06-28T13:40:00.000Z",
      },
      {
        id: "m2_d",
        sender: "me",
        text: "請問是用順豐速運嗎？",
        timestamp: "2026-06-28T13:45:00.000Z",
      },
      {
        id: "m3_d",
        sender: "them",
        text: "日本直郵，大概 3-5 天到香港，含中介保險。",
        timestamp: "2026-06-28T14:00:00.000Z",
      },
    ],
  },
];

export default INITIAL_CHATS;
