// Centralized mock members / merchants bank
import type { MarketplaceListing } from "@/app/components/marketplace/MarketplaceCard";

export type ListingStatus = "active" | "sold" | "unlisted" | "pending_trade";

export interface PublicMemberBadge {
  readonly id: string;
  readonly label: string;
  readonly emoji: string;
  readonly desc: string;
}

export interface PublicMemberReview {
  readonly id: string;
  readonly reviewer: string;
  readonly rating: number;
  readonly comment: string;
  readonly date: string;
}

export interface PublicMemberListingGrade {
  readonly authority: string;
  readonly score: string;
  readonly label?: string;
}

export interface PublicMemberPriceOfferContext {
  readonly roomId: string;
  readonly partnerName: string;
  readonly buyerName: string;
  readonly offerPrice: number;
  readonly sellerId: string;
}

export interface PublicMemberListing {
  readonly id: string; // merchant-specific listing id (LST-...)
  readonly name: string;
  readonly cardNo?: string; // aggregated product id (e.g. sv2a-182)
  readonly set: string;
  readonly rarity: "SAR" | "UR" | "SR" | "AR";
  readonly grade: PublicMemberListingGrade;
  readonly conditionLabel?: "美品 S" | "微傷 A" | "傷 B";
  readonly price: number;
  readonly delta: number;
  readonly deltaDirection: "up" | "down";
  readonly image: string;
  readonly status: ListingStatus;
  readonly paymentMethods?: string[];
  readonly shippingMethods?: string[];
  readonly createdAt?: string;
  readonly views?: number;
  readonly watchers?: number;
  readonly linkedOrderId?: string;
  readonly hasPriceOffer?: boolean;
  readonly priceOfferContext?: PublicMemberPriceOfferContext;
}

export interface PublicMemberData {
  readonly id: string;
  readonly username: string;
  readonly handle: string;
  readonly joinDate: string;
  readonly avatarSeed: string;
  readonly level: string;
  readonly levelTier?: number;
  readonly bio: string;
  readonly verifiedBuyer?: boolean;
  readonly rating: number;
  readonly reviewCount: number;
  readonly completedTrades: number;
  readonly badges: ReadonlyArray<PublicMemberBadge>;
  readonly activeListings: ReadonlyArray<PublicMemberListing>;
  readonly reviews: ReadonlyArray<PublicMemberReview>;
}

// Core merchant dataset (seed)
export const MOCK_PUBLIC_MEMBERS: Record<string, PublicMemberData> = {
  "PKT-8839-44A": {
    id: "PKT-8839-44A",
    username: "渡邊道館",
    handle: "@watanabe_gym",
    joinDate: "2024年 8月加入",
    avatarSeed: "watanabe-gym-tcg",
    level: "專業道館主",
    levelTier: 4,
    bio: "專注於第一世代 PSA 10 鑑定卡與稀有未開封補充包。保證 24 小時內發貨，所有高價卡均走平台 Escrow 鑑定託管。",
    verifiedBuyer: true,
    rating: 4.9,
    reviewCount: 124,
    completedTrades: 1204,
    badges: [
      {
        id: "top-rated",
        label: "高評分賣家",
        emoji: "⭐",
        desc: "評分維持 4.8+ 滿 30 天",
      },
      {
        id: "1000trades",
        label: "千筆交易",
        emoji: "🏆",
        desc: "累計完成 1000 筆交易",
      },
      {
        id: "fast-shipper",
        label: "閃電發貨",
        emoji: "⚡",
        desc: "平均發貨時間小於 12 小時",
      },
    ],
    activeListings: [
      {
        id: "LST-C2C-001",
        name: "Charizard ex SAR (噴火龍 ex)",
        cardNo: "sv2a-182",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10 完美鑑定" },
        conditionLabel: "美品 S",
        price: 2250,
        delta: 120,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/user-zard/200/280",
        status: "active",
        paymentMethods: ["PayMe", "轉數快 (FPS)", "現金面交"],
        shippingMethods: ["順豐到付", "市區面交"],
        createdAt: "2026/05/28",
        views: 142,
        watchers: 18,
      },
      {
        id: "LST-C2C-002",
        name: "Pikachu AR (經典肥皮卡丘)",
        cardNo: "sv2a-215",
        set: "Pokémon 151",
        rarity: "AR",
        grade: { authority: "Raw Card", score: "NM", label: "裸卡 (美品S)" },
        conditionLabel: "美品 S",
        price: 425,
        delta: 90,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/user-pika/200/280",
        status: "active",
        paymentMethods: ["轉數快 (FPS)", "現金面交"],
        shippingMethods: ["市區面交"],
        createdAt: "2026/05/25",
        views: 89,
        watchers: 5,
        linkedOrderId: "ORD-B2C-NOAUTH-004",
        hasPriceOffer: true,
        priceOfferContext: {
          roomId: "ROOM-BUYER-KOWLOON-001",
          partnerName: "九龍灣卡王",
          buyerName: "九龍灣卡王",
          offerPrice: 425,
          sellerId: "PKT-8839-44A",
        },
      },
      {
        id: "LST-C2C-003",
        name: "Mew ex SAR (復刻夢幻)",
        cardNo: "sv2a-205",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10" },
        conditionLabel: "美品 S",
        price: 900,
        delta: 150,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/user-mew/200/280",
        status: "sold",
        paymentMethods: ["PayMe"],
        shippingMethods: ["順豐速遞"],
        createdAt: "2026/05/10",
        views: 310,
        watchers: 24,
        linkedOrderId: "ORD-C2C-DONE-101",
      },
    ],
    reviews: [
      {
        id: "rev-001",
        reviewer: "K.田中",
        rating: 5,
        comment: "包裝非常謹慎，卡況與描述完全一致，快速發貨，強力推薦！",
        date: "2026年 5月",
      },
      {
        id: "rev-002",
        reviewer: "C.Lin",
        rating: 5,
        comment: "專業賣家，溝通回應快，第三次購買同一位賣家，值得信賴。",
        date: "2026年 4月",
      },
    ],
  },

  // ── New merchant profiles — all seller IDs referenced in cards.ts ────────

  "PKT-1122-33B": {
    id: "PKT-1122-33B",
    username: "旺角天線卡王",
    handle: "@mongkok_card_king",
    joinDate: "2024年 3月加入",
    avatarSeed: "mongkok-card-king",
    level: "認證商戶",
    levelTier: 2,
    bio: "旺角專業 TCG 卡牌商，主打 PSA 鑑定卡與日版限定。每週更新庫存，保證正品。",
    verifiedBuyer: true,
    rating: 4.8,
    reviewCount: 87,
    completedTrades: 652,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "top-rated",
        label: "高評分賣家",
        emoji: "⭐",
        desc: "評分維持 4.8+ 滿 30 天",
      },
    ],
    activeListings: [
      {
        id: "LST-1122-001",
        name: "Gardevoir ex SAR (沙奈朵 ex)",
        cardNo: "sv3pt5-067",
        set: "Ruler of the Black Flame",
        rarity: "SAR",
        grade: { authority: "BGS", score: "9.5", label: "BGS 9.5" },
        conditionLabel: "美品 S",
        price: 1530,
        delta: 60,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-1122/200/280",
        status: "active",
        paymentMethods: ["PayMe", "轉數快 (FPS)"],
        shippingMethods: ["順豐到付", "市區面交"],
        createdAt: "2026/05/30",
        views: 74,
        watchers: 8,
      },
    ],
    reviews: [
      {
        id: "rev-1122-001",
        reviewer: "M.Chan",
        rating: 5,
        comment: "快速出貨，包裝完善，值得信賴。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-4455-66C": {
    id: "PKT-4455-66C",
    username: "秋葉原海外直送店",
    handle: "@akiba_direct",
    joinDate: "2024年 1月加入",
    avatarSeed: "akihabara-direct",
    level: "日本代購專家",
    levelTier: 3,
    bio: "直接從秋葉原採購日版稀有卡牌，專注原盒未開封品與高等級裸卡。",
    verifiedBuyer: true,
    rating: 4.9,
    reviewCount: 203,
    completedTrades: 1890,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "1000trades",
        label: "千筆交易",
        emoji: "🏆",
        desc: "累計完成 1000 筆交易",
      },
      {
        id: "japan-import",
        label: "日本直送",
        emoji: "🇯🇵",
        desc: "日本直送認證商戶",
      },
    ],
    activeListings: [
      {
        id: "LST-4455-001",
        name: "Espeon ex SAR (太陽伊布 ex)",
        cardNo: "sv4a-348",
        set: "Shiny Treasure ex",
        rarity: "SAR",
        grade: { authority: "BGS", score: "9", label: "BGS 9" },
        conditionLabel: "美品 S",
        price: 695,
        delta: 30,
        deltaDirection: "down",
        image: "https://picsum.photos/seed/lst-4455/200/280",
        status: "active",
        paymentMethods: ["PayMe", "轉數快 (FPS)", "Stripe"],
        shippingMethods: ["順豐速遞"],
        createdAt: "2026/05/28",
        views: 112,
        watchers: 14,
      },
    ],
    reviews: [
      {
        id: "rev-4455-001",
        reviewer: "T.Yamamoto",
        rating: 5,
        comment: "日本直送，卡況完美，強力推薦！",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-7788-99D": {
    id: "PKT-7788-99D",
    username: "信和執雞大師",
    handle: "@sino_master",
    joinDate: "2023年 11月加入",
    avatarSeed: "sino-master-tcg",
    level: "資深卡牌商",
    levelTier: 3,
    bio: "信和廣場駐場超過三年，熟悉所有日本 TCG 版本，主力高稀有度鑑定卡。",
    verifiedBuyer: true,
    rating: 4.5,
    reviewCount: 156,
    completedTrades: 1120,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "1000trades",
        label: "千筆交易",
        emoji: "🏆",
        desc: "累計完成 1000 筆交易",
      },
    ],
    activeListings: [
      {
        id: "LST-7788-001",
        name: "Arceus V SAR (阿爾宙斯 V)",
        cardNo: "sv6a-085",
        set: "Stellar Miracle",
        rarity: "SAR",
        grade: { authority: "Raw Card", score: "NM", label: "裸卡美品" },
        conditionLabel: "美品 S",
        price: 3500,
        delta: 130,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-7788/200/280",
        status: "active",
        paymentMethods: ["現金面交", "轉數快 (FPS)"],
        shippingMethods: ["市區面交"],
        createdAt: "2026/05/25",
        views: 88,
        watchers: 11,
      },
    ],
    reviews: [
      {
        id: "rev-7788-001",
        reviewer: "P.Wong",
        rating: 4,
        comment: "商品如描述，溝通順暢。",
        date: "2026年 4月",
      },
    ],
  },

  "PKT-2210-55E": {
    id: "PKT-2210-55E",
    username: "深水埗精品角落",
    handle: "@shamshuipo_corner",
    joinDate: "2024年 5月加入",
    avatarSeed: "shamshuipo-corner",
    level: "精品商",
    levelTier: 1,
    bio: "深水埗老街坊，主力中低價位裸卡，庫存量大，歡迎批量詢價。",
    rating: 4.3,
    reviewCount: 42,
    completedTrades: 318,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-2210-001",
        name: "Greninja ex SAR (忍蛙 ex)",
        cardNo: "sv5a-091",
        set: "Crimson Haze",
        rarity: "SAR",
        grade: { authority: "Raw Card", score: "NM", label: "裸卡美品" },
        conditionLabel: "美品 S",
        price: 1100,
        delta: 35,
        deltaDirection: "down",
        image: "https://picsum.photos/seed/lst-2210/200/280",
        status: "active",
        paymentMethods: ["現金面交"],
        shippingMethods: ["市區面交"],
        createdAt: "2026/06/01",
        views: 33,
        watchers: 2,
      },
    ],
    reviews: [
      {
        id: "rev-2210-001",
        reviewer: "K.Lam",
        rating: 4,
        comment: "裸卡狀態良好，符合描述。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-5566-77C": {
    id: "PKT-5566-77C",
    username: "銅鑼灣收藏家",
    handle: "@cwb_collector",
    joinDate: "2023年 9月加入",
    avatarSeed: "cwb-collector-hk",
    level: "頂級鑑賞家",
    levelTier: 4,
    bio: "銅鑼灣高端收藏家，只收 PSA 10 極品，不賣不精品。收藏超過 500 張 PSA 10 鑑定卡。",
    verifiedBuyer: true,
    rating: 5.0,
    reviewCount: 98,
    completedTrades: 874,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "top-rated",
        label: "高評分賣家",
        emoji: "⭐",
        desc: "評分維持 4.8+ 滿 30 天",
      },
      {
        id: "psa10-specialist",
        label: "PSA 10 專家",
        emoji: "💎",
        desc: "主力 PSA 10 鑑定卡商戶",
      },
    ],
    activeListings: [
      {
        id: "LST-5566-001",
        name: "Mew ex SAR (夢幻 ex)",
        cardNo: "sv2a-205",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10" },
        conditionLabel: "美品 S",
        price: 1050,
        delta: 85,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-5566/200/280",
        status: "active",
        paymentMethods: ["Stripe", "轉數快 (FPS)"],
        shippingMethods: ["順豐速遞"],
        createdAt: "2026/05/29",
        views: 156,
        watchers: 21,
      },
    ],
    reviews: [
      {
        id: "rev-5566-001",
        reviewer: "H.Nakamura",
        rating: 5,
        comment: "頂級收藏家，商品無懈可擊。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-9900-11A": {
    id: "PKT-9900-11A",
    username: "尖沙咀卡神",
    handle: "@tsim_card_god",
    joinDate: "2023年 6月加入",
    avatarSeed: "tsimshatsui-card-god",
    level: "黃金商戶",
    levelTier: 4,
    bio: "尖沙咀老牌卡牌神店，日本 TCG 一手代理，主力 SR 至 SAR 高稀有度鑑定卡。",
    verifiedBuyer: true,
    rating: 4.9,
    reviewCount: 312,
    completedTrades: 2840,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "1000trades",
        label: "千筆交易",
        emoji: "🏆",
        desc: "累計完成 1000 筆交易",
      },
      {
        id: "top-rated",
        label: "高評分賣家",
        emoji: "⭐",
        desc: "評分維持 4.8+ 滿 30 天",
      },
    ],
    activeListings: [
      {
        id: "LST-9900-001",
        name: "Lugia V SAR (盧基亞 V)",
        cardNo: "sv4pt5-086",
        set: "Paradigm Trigger",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10" },
        conditionLabel: "美品 S",
        price: 2900,
        delta: 110,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-9900/200/280",
        status: "active",
        paymentMethods: ["Stripe", "PayMe", "轉數快 (FPS)"],
        shippingMethods: ["順豐速遞", "順豐到付"],
        createdAt: "2026/05/31",
        views: 220,
        watchers: 30,
      },
    ],
    reviews: [
      {
        id: "rev-9900-001",
        reviewer: "C.Suzuki",
        rating: 5,
        comment: "交易全程專業，快速到貨，強烈推薦！",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-3311-22D": {
    id: "PKT-3311-22D",
    username: "荔枝角大師傅",
    handle: "@lck_master",
    joinDate: "2024年 2月加入",
    avatarSeed: "laichikok-master",
    level: "認證商戶",
    levelTier: 2,
    bio: "荔枝角社區卡牌老師傅，主力 CGC 鑑定卡，價格實惠，服務友善。",
    rating: 4.6,
    reviewCount: 68,
    completedTrades: 482,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-3311-001",
        name: "Iron Hands ex SAR (鋼鐵拳頭 ex)",
        cardNo: "sv3h-091",
        set: "Cyber Judge",
        rarity: "SAR",
        grade: { authority: "CGC", score: "9", label: "CGC 9" },
        conditionLabel: "微傷 A",
        price: 1300,
        delta: 25,
        deltaDirection: "down",
        image: "https://picsum.photos/seed/lst-3311/200/280",
        status: "active",
        paymentMethods: ["轉數快 (FPS)", "現金面交"],
        shippingMethods: ["市區面交"],
        createdAt: "2026/06/02",
        views: 45,
        watchers: 4,
      },
    ],
    reviews: [
      {
        id: "rev-3311-001",
        reviewer: "B.Leung",
        rating: 5,
        comment: "師傅人好，卡況如實描述，滿意！",
        date: "2026年 4月",
      },
    ],
  },

  "PKT-2233-44B": {
    id: "PKT-2233-44B",
    username: "元朗李生精品",
    handle: "@ylt_mr_lee",
    joinDate: "2024年 4月加入",
    avatarSeed: "yuenlong-mrlee",
    level: "精品商",
    levelTier: 1,
    bio: "元朗地區老字號精品店，主力日版裸卡，兼收購所有稀有度。",
    rating: 4.7,
    reviewCount: 55,
    completedTrades: 390,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-2233-001",
        name: "Venusaur ex SAR (妙蛙花 ex)",
        cardNo: "sv2a-236",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "BGS", score: "9.5", label: "BGS 9.5" },
        conditionLabel: "美品 S",
        price: 1800,
        delta: 45,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-2233/200/280",
        status: "active",
        paymentMethods: ["轉數快 (FPS)", "現金面交"],
        shippingMethods: ["市區面交", "順豐到付"],
        createdAt: "2026/05/28",
        views: 62,
        watchers: 7,
      },
    ],
    reviews: [
      {
        id: "rev-2233-001",
        reviewer: "A.Cheung",
        rating: 5,
        comment: "李生態度好，卡況超過預期。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-8866-00C": {
    id: "PKT-8866-00C",
    username: "觀塘夜市收藏王",
    handle: "@kwuntong_night",
    joinDate: "2023年 12月加入",
    avatarSeed: "kwuntong-night-market",
    level: "夜市王牌商",
    levelTier: 2,
    bio: "觀塘夜市第一卡牌攤位，每晚更新庫存，主力 PSA 10 與 BGS 9.5 鑑定卡。",
    verifiedBuyer: true,
    rating: 4.6,
    reviewCount: 79,
    completedTrades: 610,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "night-market",
        label: "夜市王牌",
        emoji: "🌙",
        desc: "觀塘夜市認證攤位",
      },
    ],
    activeListings: [
      {
        id: "LST-8866-001",
        name: "Gardevoir ex SAR (沙奈朵 ex)",
        cardNo: "sv3pt5-067",
        set: "Ruler of the Black Flame",
        rarity: "SAR",
        grade: { authority: "Raw Card", score: "NM", label: "裸卡美品" },
        conditionLabel: "美品 S",
        price: 1420,
        delta: 60,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-8866/200/280",
        status: "active",
        paymentMethods: ["現金面交"],
        shippingMethods: ["市區面交"],
        createdAt: "2026/06/03",
        views: 56,
        watchers: 5,
      },
    ],
    reviews: [
      {
        id: "rev-8866-001",
        reviewer: "G.Ho",
        rating: 5,
        comment: "夜市買到靚卡，物超所值！",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-6644-88A": {
    id: "PKT-6644-88A",
    username: "新宿夜行商",
    handle: "@shinjuku_night_dealer",
    joinDate: "2023年 8月加入",
    avatarSeed: "shinjuku-night-dealer",
    level: "日本黃金商戶",
    levelTier: 4,
    bio: "東京新宿夜場精品卡牌商，每月親赴日本採購，主力 PSA 10 與全系列新版。",
    verifiedBuyer: true,
    rating: 5.0,
    reviewCount: 215,
    completedTrades: 1980,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "1000trades",
        label: "千筆交易",
        emoji: "🏆",
        desc: "累計完成 1000 筆交易",
      },
      {
        id: "japan-import",
        label: "日本直送",
        emoji: "🇯🇵",
        desc: "日本直送認證商戶",
      },
      {
        id: "top-rated",
        label: "高評分賣家",
        emoji: "⭐",
        desc: "評分維持 4.8+ 滿 30 天",
      },
    ],
    activeListings: [
      {
        id: "LST-6644-001",
        name: "Lugia V SAR (盧基亞 V)",
        cardNo: "sv4pt5-086",
        set: "Paradigm Trigger",
        rarity: "SAR",
        grade: { authority: "BGS", score: "9.5", label: "BGS 9.5" },
        conditionLabel: "美品 S",
        price: 2750,
        delta: 110,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-6644/200/280",
        status: "active",
        paymentMethods: ["Stripe", "PayMe"],
        shippingMethods: ["順豐速遞"],
        createdAt: "2026/05/30",
        views: 188,
        watchers: 25,
      },
    ],
    reviews: [
      {
        id: "rev-6644-001",
        reviewer: "Y.Tanaka",
        rating: 5,
        comment: "新宿大師，交易一流，日本直送毫無疑問。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-1188-22E": {
    id: "PKT-1188-22E",
    username: "石籬二手精品鋪",
    handle: "@shekleicorner",
    joinDate: "2024年 6月加入",
    avatarSeed: "shekkei-secondhand",
    level: "精品商",
    levelTier: 1,
    bio: "石籬社區老鋪，主打二手卡牌回收與轉讓，CGC 鑑定卡定期上新。",
    rating: 4.7,
    reviewCount: 38,
    completedTrades: 265,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-1188-001",
        name: "Arceus V SAR (阿爾宙斯 V)",
        cardNo: "sv6a-085",
        set: "Stellar Miracle",
        rarity: "SAR",
        grade: { authority: "BGS", score: "9.5", label: "BGS 9.5" },
        conditionLabel: "美品 S",
        price: 3750,
        delta: 130,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-1188/200/280",
        status: "active",
        paymentMethods: ["轉數快 (FPS)"],
        shippingMethods: ["順豐到付"],
        createdAt: "2026/05/29",
        views: 91,
        watchers: 12,
      },
    ],
    reviews: [
      {
        id: "rev-1188-001",
        reviewer: "F.Kwok",
        rating: 5,
        comment: "二手鋪出品，卡況意外地好。",
        date: "2026年 4月",
      },
    ],
  },

  "PKT-7755-99B": {
    id: "PKT-7755-99B",
    username: "大阪神秘珍品室",
    handle: "@osaka_mystery_room",
    joinDate: "2023年 10月加入",
    avatarSeed: "osaka-mystery-room",
    level: "日本黃金商戶",
    levelTier: 3,
    bio: "大阪神秘珍品室，專注日本本地稀有版本與限定套裝，BGS 9.5 品質保證。",
    verifiedBuyer: true,
    rating: 4.8,
    reviewCount: 142,
    completedTrades: 1340,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "1000trades",
        label: "千筆交易",
        emoji: "🏆",
        desc: "累計完成 1000 筆交易",
      },
      {
        id: "japan-import",
        label: "日本直送",
        emoji: "🇯🇵",
        desc: "日本直送認證商戶",
      },
    ],
    activeListings: [
      {
        id: "LST-7755-001",
        name: "Iron Hands ex SAR (鋼鐵拳頭 ex)",
        cardNo: "sv3h-091",
        set: "Cyber Judge",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10" },
        conditionLabel: "美品 S",
        price: 1380,
        delta: 25,
        deltaDirection: "down",
        image: "https://picsum.photos/seed/lst-7755/200/280",
        status: "active",
        paymentMethods: ["Stripe", "PayMe"],
        shippingMethods: ["順豐速遞"],
        createdAt: "2026/05/27",
        views: 103,
        watchers: 13,
      },
    ],
    reviews: [
      {
        id: "rev-7755-001",
        reviewer: "D.Matsui",
        rating: 5,
        comment: "大阪直輸入，品質超標，讚！",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-9977-11D": {
    id: "PKT-9977-11D",
    username: "九龍城無框生品",
    handle: "@klncity_raw",
    joinDate: "2024年 7月加入",
    avatarSeed: "kowlooncity-raw",
    level: "裸卡專家",
    levelTier: 1,
    bio: "九龍城專攻裸卡市場，低溢價、高流動性，適合買家自行送鑑定。",
    rating: 4.4,
    reviewCount: 27,
    completedTrades: 195,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-9977-001",
        name: "Espeon ex SAR (太陽伊布 ex)",
        cardNo: "sv4a-348",
        set: "Shiny Treasure ex",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10" },
        conditionLabel: "美品 S",
        price: 720,
        delta: 30,
        deltaDirection: "down",
        image: "https://picsum.photos/seed/lst-9977/200/280",
        status: "active",
        paymentMethods: ["現金面交"],
        shippingMethods: ["市區面交"],
        createdAt: "2026/06/04",
        views: 29,
        watchers: 2,
      },
    ],
    reviews: [
      {
        id: "rev-9977-001",
        reviewer: "R.Poon",
        rating: 4,
        comment: "裸卡狀態良好，值回票價。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-5544-77C": {
    id: "PKT-5544-77C",
    username: "元朗動漫城",
    handle: "@ylt_anime_city",
    joinDate: "2023年 7月加入",
    avatarSeed: "yuenlong-anime-city",
    level: "認證商戶",
    levelTier: 2,
    bio: "元朗動漫城卡牌部門，主力各系列寶可夢 TCG，歡迎實體門市選購。",
    verifiedBuyer: true,
    rating: 4.9,
    reviewCount: 134,
    completedTrades: 1050,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "1000trades",
        label: "千筆交易",
        emoji: "🏆",
        desc: "累計完成 1000 筆交易",
      },
    ],
    activeListings: [
      {
        id: "LST-5544-001",
        name: "Venusaur ex SAR (妙蛙花 ex)",
        cardNo: "sv2a-236",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10" },
        conditionLabel: "美品 S",
        price: 1850,
        delta: 45,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-5544/200/280",
        status: "active",
        paymentMethods: ["Stripe", "PayMe", "現金面交"],
        shippingMethods: ["順豐速遞", "市區面交"],
        createdAt: "2026/05/28",
        views: 116,
        watchers: 16,
      },
    ],
    reviews: [
      {
        id: "rev-5544-001",
        reviewer: "L.Chan",
        rating: 5,
        comment: "動漫城品質有保證，推薦！",
        date: "2026年 4月",
      },
    ],
  },

  "PKT-3322-55A": {
    id: "PKT-3322-55A",
    username: "西環電力站",
    handle: "@saiyingpun_power",
    joinDate: "2024年 1月加入",
    avatarSeed: "sai-ying-pun-power",
    level: "認證商戶",
    levelTier: 2,
    bio: "西環電力站卡牌鋪，主力電系寶可夢卡牌，CGC 與 PSA 混合庫存。",
    rating: 4.8,
    reviewCount: 73,
    completedTrades: 560,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "top-rated",
        label: "高評分賣家",
        emoji: "⭐",
        desc: "評分維持 4.8+ 滿 30 天",
      },
    ],
    activeListings: [
      {
        id: "LST-3322-001",
        name: "Sylveon ex SAR (妮可伊布 ex)",
        cardNo: "sv4a-191",
        set: "Shiny Treasure ex",
        rarity: "SAR",
        grade: { authority: "CGC", score: "9.5", label: "CGC 9.5" },
        conditionLabel: "美品 S",
        price: 860,
        delta: 40,
        deltaDirection: "down",
        image: "https://picsum.photos/seed/lst-3322/200/280",
        status: "active",
        paymentMethods: ["PayMe", "轉數快 (FPS)"],
        shippingMethods: ["順豐到付"],
        createdAt: "2026/05/31",
        views: 68,
        watchers: 9,
      },
    ],
    reviews: [
      {
        id: "rev-3322-001",
        reviewer: "S.Tsang",
        rating: 5,
        comment: "電力站出品，電系卡款最齊全！",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-4433-66B": {
    id: "PKT-4433-66B",
    username: "藍田玩具商",
    handle: "@lantian_toy",
    joinDate: "2024年 3月加入",
    avatarSeed: "lantian-toy-shop",
    level: "精品商",
    levelTier: 1,
    bio: "藍田玩具店附設卡牌部，主力中價位 PSA 9 與 CGC 9 鑑定卡，適合入門收藏。",
    rating: 4.5,
    reviewCount: 48,
    completedTrades: 342,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-4433-001",
        name: "Sylveon ex SAR (妮可伊布 ex)",
        cardNo: "sv4a-191",
        set: "Shiny Treasure ex",
        rarity: "SAR",
        grade: { authority: "PSA", score: "9", label: "PSA 9" },
        conditionLabel: "微傷 A",
        price: 820,
        delta: 40,
        deltaDirection: "down",
        image: "https://picsum.photos/seed/lst-4433/200/280",
        status: "active",
        paymentMethods: ["現金面交", "轉數快 (FPS)"],
        shippingMethods: ["市區面交"],
        createdAt: "2026/06/01",
        views: 41,
        watchers: 3,
      },
    ],
    reviews: [
      {
        id: "rev-4433-001",
        reviewer: "N.Ip",
        rating: 4,
        comment: "玩具商出品卡牌，性價比高。",
        date: "2026年 4月",
      },
    ],
  },

  "PKT-6655-88D": {
    id: "PKT-6655-88D",
    username: "將軍澳小卡鋪",
    handle: "@tseung_kwan_o_cards",
    joinDate: "2024年 8月加入",
    avatarSeed: "tko-small-card-shop",
    level: "精品商",
    levelTier: 1,
    bio: "將軍澳區小型卡牌鋪，主力裸卡與入門級鑑定卡，價格親民，歡迎新手。",
    rating: 4.2,
    reviewCount: 21,
    completedTrades: 148,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-6655-001",
        name: "Venusaur ex SAR (妙蛙花 ex)",
        cardNo: "sv2a-236",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "PSA", score: "9", label: "PSA 9" },
        conditionLabel: "微傷 A",
        price: 1750,
        delta: 45,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-6655/200/280",
        status: "active",
        paymentMethods: ["轉數快 (FPS)"],
        shippingMethods: ["順豐到付"],
        createdAt: "2026/06/02",
        views: 24,
        watchers: 1,
      },
    ],
    reviews: [
      {
        id: "rev-6655-001",
        reviewer: "O.Fong",
        rating: 4,
        comment: "小鋪用心，下次再幫趁。",
        date: "2026年 5月",
      },
    ],
  },

  // ── 8 新增賣家：擴展 sv2a-182 掛單簿至 13 筆 ─────────────────────────────

  "PKT-3366-88F": {
    id: "PKT-3366-88F",
    username: "北角高層收藏所",
    handle: "@northpoint_high_collect",
    joinDate: "2024年 2月加入",
    avatarSeed: "northpoint-high",
    level: "認證商戶",
    levelTier: 2,
    bio: "北角高層商業中心頂級收藏室，主力 PSA 10 鑑定卡，預約制限定上架。",
    verifiedBuyer: true,
    rating: 4.7,
    reviewCount: 61,
    completedTrades: 445,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-3366-001",
        name: "Charizard ex SAR (噴火龍 ex)",
        cardNo: "sv2a-182",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10" },
        conditionLabel: "美品 S",
        price: 2350,
        delta: 120,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-3366/200/280",
        status: "active",
        paymentMethods: ["Stripe", "轉數快 (FPS)"],
        shippingMethods: ["順豐速遞"],
        createdAt: "2026/05/30",
        views: 80,
        watchers: 9,
      },
    ],
    reviews: [
      {
        id: "rev-3366-001",
        reviewer: "W.Kwan",
        rating: 5,
        comment: "高層收藏室，品質一流。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-5577-22G": {
    id: "PKT-5577-22G",
    username: "大坑珍品屋",
    handle: "@taikeng_treasure",
    joinDate: "2023年 11月加入",
    avatarSeed: "tai-hang-treasure",
    level: "認證商戶",
    levelTier: 2,
    bio: "大坑小街精品珍品屋，主力 BGS 9.5 鑑定卡，每月限量上架。",
    verifiedBuyer: true,
    rating: 4.8,
    reviewCount: 84,
    completedTrades: 672,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "top-rated",
        label: "高評分賣家",
        emoji: "⭐",
        desc: "評分維持 4.8+ 滿 30 天",
      },
    ],
    activeListings: [
      {
        id: "LST-5577-001",
        name: "Charizard ex SAR (噴火龍 ex)",
        cardNo: "sv2a-182",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "BGS", score: "9.5", label: "BGS 9.5" },
        conditionLabel: "美品 S",
        price: 2200,
        delta: 120,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-5577/200/280",
        status: "active",
        paymentMethods: ["PayMe", "轉數快 (FPS)"],
        shippingMethods: ["順豐到付"],
        createdAt: "2026/05/31",
        views: 95,
        watchers: 11,
      },
    ],
    reviews: [
      {
        id: "rev-5577-001",
        reviewer: "I.Chow",
        rating: 5,
        comment: "大坑珍品，每次買都滿意。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-6622-11H": {
    id: "PKT-6622-11H",
    username: "灣仔潮流卡舖",
    handle: "@wanchai_trendy_cards",
    joinDate: "2024年 4月加入",
    avatarSeed: "wanchai-trendy",
    level: "精品商",
    levelTier: 1,
    bio: "灣仔潮流卡舖，緊跟市場動向，裸卡庫存量大，每週補貨。",
    rating: 4.4,
    reviewCount: 33,
    completedTrades: 238,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-6622-001",
        name: "Charizard ex SAR (噴火龍 ex)",
        cardNo: "sv2a-182",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "Raw Card", score: "NM", label: "裸卡美品" },
        conditionLabel: "美品 S",
        price: 1900,
        delta: 120,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-6622/200/280",
        status: "active",
        paymentMethods: ["現金面交", "轉數快 (FPS)"],
        shippingMethods: ["市區面交"],
        createdAt: "2026/06/02",
        views: 44,
        watchers: 3,
      },
    ],
    reviews: [
      {
        id: "rev-6622-001",
        reviewer: "J.Ng",
        rating: 4,
        comment: "灣仔靚卡，下次再嚟。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-9911-33I": {
    id: "PKT-9911-33I",
    username: "天水圍拍賣商",
    handle: "@tinshuiwai_auction",
    joinDate: "2024年 5月加入",
    avatarSeed: "tin-shui-wai-auction",
    level: "精品商",
    levelTier: 1,
    bio: "天水圍在地拍賣商，擅長以競拍形式出售稀有卡牌，CGC 鑑定卡為主。",
    rating: 4.6,
    reviewCount: 29,
    completedTrades: 207,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-9911-001",
        name: "Miraidon ex SAR (未來電龍 ex)",
        cardNo: "sv4k-079",
        set: "Future Flash",
        rarity: "SAR",
        grade: { authority: "BGS", score: "9.5", label: "BGS 9.5" },
        conditionLabel: "美品 S",
        price: 1870,
        delta: 70,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-9911/200/280",
        status: "active",
        paymentMethods: ["轉數快 (FPS)"],
        shippingMethods: ["順豐到付"],
        createdAt: "2026/06/01",
        views: 37,
        watchers: 4,
      },
    ],
    reviews: [
      {
        id: "rev-9911-001",
        reviewer: "Q.Liu",
        rating: 5,
        comment: "拍賣競得靚卡，體驗不俗。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-4477-66J": {
    id: "PKT-4477-66J",
    username: "東涌海外代購",
    handle: "@tung_chung_import",
    joinDate: "2024年 1月加入",
    avatarSeed: "tung-chung-import",
    level: "海外代購商",
    levelTier: 2,
    bio: "東涌機場附近代購中心，主力日本、韓國及美版高等級鑑定卡直送服務。",
    verifiedBuyer: true,
    rating: 4.5,
    reviewCount: 57,
    completedTrades: 418,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "japan-import",
        label: "日本直送",
        emoji: "🇯🇵",
        desc: "日本直送認證商戶",
      },
    ],
    activeListings: [
      {
        id: "LST-4477-001",
        name: "Charizard ex SAR (噴火龍 ex)",
        cardNo: "sv2a-182",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "PSA", score: "9", label: "PSA 9" },
        conditionLabel: "微傷 A",
        price: 1970,
        delta: 120,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-4477/200/280",
        status: "active",
        paymentMethods: ["Stripe", "轉數快 (FPS)"],
        shippingMethods: ["順豐速遞"],
        createdAt: "2026/05/29",
        views: 68,
        watchers: 7,
      },
    ],
    reviews: [
      {
        id: "rev-4477-001",
        reviewer: "V.Au",
        rating: 5,
        comment: "東涌代購快捷可靠，一試難忘。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-7733-55K": {
    id: "PKT-7733-55K",
    username: "屯門古稀精品",
    handle: "@tuenmun_antique",
    joinDate: "2024年 3月加入",
    avatarSeed: "tuen-mun-antique",
    level: "精品商",
    levelTier: 2,
    bio: "屯門古稀精品主打舊版與古稀稀有卡牌，BGS 9 精選庫存，專為資深收藏家而設。",
    rating: 4.3,
    reviewCount: 36,
    completedTrades: 258,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-7733-001",
        name: "Koraidon ex SAR (古代威武雄 ex)",
        cardNo: "sv5d-107",
        set: "Ancient Roar",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10" },
        conditionLabel: "美品 S",
        price: 1700,
        delta: 55,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-7733/200/280",
        status: "active",
        paymentMethods: ["轉數快 (FPS)", "現金面交"],
        shippingMethods: ["市區面交", "順豐到付"],
        createdAt: "2026/05/30",
        views: 53,
        watchers: 5,
      },
    ],
    reviews: [
      {
        id: "rev-7733-001",
        reviewer: "U.Ma",
        rating: 4,
        comment: "古稀精品，品質有保障。",
        date: "2026年 4月",
      },
    ],
  },

  "PKT-1199-44L": {
    id: "PKT-1199-44L",
    username: "荃灣TCG Gallery",
    handle: "@twgallery_tcg",
    joinDate: "2023年 9月加入",
    avatarSeed: "tsuen-wan-tcg-gallery",
    level: "黃金商戶",
    levelTier: 3,
    bio: "荃灣 TCG Gallery，首選收藏家投資組合顧問，主力 PSA 10 高端鑑定卡庫存。",
    verifiedBuyer: true,
    rating: 4.9,
    reviewCount: 178,
    completedTrades: 1560,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
      {
        id: "1000trades",
        label: "千筆交易",
        emoji: "🏆",
        desc: "累計完成 1000 筆交易",
      },
      {
        id: "top-rated",
        label: "高評分賣家",
        emoji: "⭐",
        desc: "評分維持 4.8+ 滿 30 天",
      },
    ],
    activeListings: [
      {
        id: "LST-1199-001",
        name: "Charizard ex SAR (噴火龍 ex)",
        cardNo: "sv2a-182",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "PSA", score: "10", label: "PSA 10" },
        conditionLabel: "美品 S",
        price: 2420,
        delta: 120,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-1199/200/280",
        status: "active",
        paymentMethods: ["Stripe", "PayMe", "轉數快 (FPS)"],
        shippingMethods: ["順豐速遞"],
        createdAt: "2026/05/28",
        views: 143,
        watchers: 20,
      },
    ],
    reviews: [
      {
        id: "rev-1199-001",
        reviewer: "X.Yuen",
        rating: 5,
        comment: "Gallery 級別服務，交易全程無憂。",
        date: "2026年 5月",
      },
    ],
  },

  "PKT-8844-77M": {
    id: "PKT-8844-77M",
    username: "沙田競技商城",
    handle: "@shatin_arena",
    joinDate: "2024年 6月加入",
    avatarSeed: "shatin-arena-shop",
    level: "精品商",
    levelTier: 1,
    bio: "沙田競技商城卡牌部門，主力中低價位裸卡，賽事選手專用備牌補貨首選。",
    rating: 4.2,
    reviewCount: 19,
    completedTrades: 135,
    badges: [
      {
        id: "verified",
        label: "已認證商戶",
        emoji: "✅",
        desc: "平台身份已驗證",
      },
    ],
    activeListings: [
      {
        id: "LST-8844-001",
        name: "Charizard ex SAR (噴火龍 ex)",
        cardNo: "sv2a-182",
        set: "Pokémon 151",
        rarity: "SAR",
        grade: { authority: "Raw Card", score: "NM", label: "裸卡美品" },
        conditionLabel: "美品 S",
        price: 1860,
        delta: 120,
        deltaDirection: "up",
        image: "https://picsum.photos/seed/lst-8844/200/280",
        status: "active",
        paymentMethods: ["轉數快 (FPS)", "現金面交"],
        shippingMethods: ["市區面交"],
        createdAt: "2026/06/03",
        views: 27,
        watchers: 1,
      },
    ],
    reviews: [
      {
        id: "rev-8844-001",
        reviewer: "Z.Hui",
        rating: 4,
        comment: "競技商城出品，賽事備牌首選。",
        date: "2026年 5月",
      },
    ],
  },
};

export function getPublicMemberById(id: string) {
  return MOCK_PUBLIC_MEMBERS[id] ?? null;
}

// Convert internal merchant listing into storefront listing used by merchant storefront UI
export function getStorefrontListingsByMember(
  member: PublicMemberData,
): MarketplaceListing[] {
  return member.activeListings
    .filter((l) => l.status === "active")
    .map((listing) => ({
      id: listing.id, // merchant-specific listing id (preserve LST-... id for private storefront routes)
      cardNo: listing.cardNo,
      name: listing.name,
      set: listing.set,
      rarity: listing.rarity,
      grade: { authority: listing.grade.authority, score: listing.grade.score },
      conditionLabel: listing.conditionLabel,
      price: listing.price,
      delta: listing.delta,
      deltaDirection: listing.deltaDirection,
      image: listing.image,
      seller: member.username,
      sellerId: member.id,
      detailHref: `/marketplace/${member.id}/product/${listing.id}`,
    }));
}

export default MOCK_PUBLIC_MEMBERS;
